_target_: src.models.bscan_classification_v2_module.BscanClassificationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.000001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10


model_name: efficientnet_b1

pretrained: true

num_classes: 1
# compile model for faster training with pytorch 2.0
compile: false
